RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Amazon DynamoDB Workshop & Labs"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false

uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"



[params]
  editURL = "https://github.com/aws-samples/amazon-dynamodb-labs/blob/master/content/"
  description = "Hands on labs and real world design scenarios for Amazon DynamoDB"
  author = "Sean Shriver"
  disableBreadcrumb = false
  disableNextPrev = false
  showVisitedLinks = true
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = true
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true
  #AWS custom params
  design_patterns_s3_lab_yaml = "https://s3.amazonaws.com/amazon-dynamodb-labs.com/assets/lab.yaml"
  latest_rh_design_pattern_yt = "https://www.youtube.com/watch?v=6yqfmXiZTlM"
  github_contributing_guide = "https://github.com/aws-samples/amazon-dynamodb-labs/blob/master/CONTRIBUTING.md"
  github_issues_link = "https://github.com/aws-samples/amazon-dynamodb-labs/issues"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true

#
[menu]
[[menu.shortcuts]]
name = "<i class='fab fa-github'></i>&nbsp;&nbsp;Contributing (GitHub)"
url = "https://github.com/aws-samples/amazon-dynamodb-labs/blob/master/CONTRIBUTING.md"
weight = 2

[[menu.shortcuts]]
name = "<i class='fas fa-users'></i>&nbsp;Authors"
url = "/authors.html"
weight = 3



[Languages]
[Languages.en]
title = "Amazon DynamoDB Workshop & Labs"
weight = 1
languageName = "English"
